// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2uITVdKL-Gfe6Ao4u27DGtxKTzFq00Pk',
    appId: '1:441393091992:web:71c7c4720a70d87077c7ed',
    messagingSenderId: '441393091992',
    projectId: 'realhero-6df71',
    authDomain: 'realhero-6df71.firebaseapp.com',
    storageBucket: 'realhero-6df71.appspot.com',
    measurementId: 'G-FBLZD1G8FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB4HlOdxhDIFR7ml9R7mjBxLplTTVTQJU',
    appId: '1:441393091992:android:af7a6f4adfff199c77c7ed',
    messagingSenderId: '441393091992',
    projectId: 'realhero-6df71',
    storageBucket: 'realhero-6df71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzxcT4hdCt7q4WWxwY_DHqmYD2_30lloY',
    appId: '1:441393091992:ios:b70492e66432d95177c7ed',
    messagingSenderId: '441393091992',
    projectId: 'realhero-6df71',
    storageBucket: 'realhero-6df71.appspot.com',
    iosBundleId: 'com.example.realhero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzxcT4hdCt7q4WWxwY_DHqmYD2_30lloY',
    appId: '1:441393091992:ios:b70492e66432d95177c7ed',
    messagingSenderId: '441393091992',
    projectId: 'realhero-6df71',
    storageBucket: 'realhero-6df71.appspot.com',
    iosBundleId: 'com.example.realhero',
  );
}
